# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30  # Évite les runs bloqués

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0 # Pour avoir tout l'historique git

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Validate POM
      run: mvn validate -f TourGuide/pom.xml

    - name: Install external JARs
      run: |
        mvn install:install-file -Dfile=TourGuide/libs/gpsUtil.jar -DgroupId=gpsUtil -DartifactId=gpsUtil -Dversion=1.0.0 -Dpackaging=jar
        mvn install:install-file -Dfile=TourGuide/libs/RewardCentral.jar -DgroupId=rewardCentral -DartifactId=rewardCentral -Dversion=1.0.0 -Dpackaging=jar
        mvn install:install-file -Dfile=TourGuide/libs/TripPricer.jar -DgroupId=tripPricer -DartifactId=tripPricer -Dversion=1.0.0 -Dpackaging=jar

    - name: Build with Maven
      run: mvn -B package -f TourGuide/pom.xml

    - name: Upload build artifact
      if: success()  # Ne s'exécute que si le build réussit
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: TourGuide/target/*.jar
        retention-days: 7

    - name: Run tests with coverage
      run: mvn -B verify -f TourGuide/pom.xml

    - name: Upload test results
      if: always()  # S'exécute même si les tests échouent
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: TourGuide/target/surefire-reports/
